### ISSUE TITLE
Onboarding new AIDA Data Hub staff

### ISSUE THREAD

**Issue by yohell** [NBISweden/aida-data-hub#2]
- [ ] Figure out training needs
- [ ] Get people an office space and equipment
- [ ] Get people accounts
- [ ] Compile self-study materials
