### ISSUE TITLE
Help SCAPIS share imaging data through the AIDA Data Hub DGX-2 service

### ISSUE THREAD

**Issue by yohell** [NBISweden/aida-data-hub#7]
Göran (SCAPIS dir) has appointed Elizabeth Norseng as our SCAPIS contact here, who has proposed a roadmap that is currently being refined and implemented.

It contains 
* [x] uploading pilot dataset aida3000
* [x] sharing the aida3000 dataset with a pilot researcher, using proper routines
* [x] transfer the full amount of data from "stor NAS" to DGX-2.
